# Generated by Django 4.0.3 on 2022-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCompaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('organizer_name', models.CharField(max_length=45)),
                ('date', models.DateField()),
            ],
        ),
    ]
