# Generated by Django 4.0.3 on 2022-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_healthcompaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcompaign',
            name='pic_name',
            field=models.ImageField(default='', max_length=225, upload_to='healthapp/campaign_pic'),
        ),
    ]
