# Generated by Django 4.0.3 on 2022-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=45)),
                ('experttype', models.CharField(max_length=45)),
                ('pic_name', models.FileField(default='', upload_to='healthapp/campaign_pic')),
            ],
        ),
    ]
