# Generated by Django 4.0.3 on 2022-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_healthexpert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='healthexpert',
            name='pic_name',
            field=models.FileField(default='', upload_to='healthapp/Healthexpert_pic'),
        ),
    ]
