# Generated by Django 4.0.3 on 2022-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_patient_alter_healthexpert_pic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthexpert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='healthexpert',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='healthexpert',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
