# Generated by Django 4.0.3 on 2022-04-04 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_remove_user_message_user1_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tips_contents', models.TextField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.healthexpert')),
            ],
        ),
    ]
