# Generated by Django 4.0.3 on 2022-04-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0012_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='expert_user_name',
            field=models.CharField(default='abc ', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthapp.patient'),
        ),
    ]
